{"name": "test_get_combined_field_and_source_xds_ephemeris_empty", "status": "passed", "description": "Test that get_combined_field_and_source_xds with ephemeris raises an exception on empty DataTree", "start": 1757016773833, "stop": 1757016773833, "uuid": "34d60da8-460c-492d-9ab2-efe683c1862c", "historyId": "115483b5fdf2795834d17a86b081ccd2", "testCaseId": "115483b5fdf2795834d17a86b081ccd2", "fullName": "tests.unit.measurement_set.test_processing_set_xdt.TestProcessingSetXdtErrors#test_get_combined_field_and_source_xds_ephemeris_empty", "labels": [{"name": "parentSuite", "value": "tests.unit.measurement_set"}, {"name": "suite", "value": "test_processing_set_xdt"}, {"name": "subSuite", "value": "TestProcessingSetXdtErrors"}, {"name": "host", "value": "pkrvm7jw40e0xgp"}, {"name": "thread", "value": "3826-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.measurement_set.test_processing_set_xdt"}], "titlePath": ["tests", "unit", "measurement_set", "test_processing_set_xdt.py", "TestProcessingSetXdtErrors"]}