INFO     testviper.rp_reporter:testviper_rp_reporter.py:223 TestViper RP: Starting test toolviper/tests/test_menerva.py::TestToolViperMenerva::test_thread_info
INFO     testviper.rp_reporter:testviper_rp_reporter.py:229 TestViper RP: Executing test toolviper/tests/test_menerva.py::TestToolViperMenerva::test_thread_info
INFO     viperlog:parameter.py:227 Module path: [38;2;50;50;205m/home/runner/work/testviper/testviper/src/toolviper[0m
WARNING  viperlog:logger.py:109 It is recommended that the local cache directory be set using the [38;2;50;50;205mdask_local_dir[0m parameter.
INFO     distributed.scheduler:scheduler.py:1766 State start
INFO     distributed.scheduler:scheduler.py:4282   Scheduler at:     tcp://127.0.0.1:41767
INFO     distributed.scheduler:scheduler.py:4297   dashboard at:  http://127.0.0.1:8787/status
INFO     distributed.scheduler:scheduler.py:8182 Registering Worker plugin shuffle
INFO     distributed.nanny:nanny.py:368         Start Nanny at: 'tcp://127.0.0.1:37567'
INFO     distributed.nanny:nanny.py:368         Start Nanny at: 'tcp://127.0.0.1:42147'
INFO     distributed.scheduler:scheduler.py:4635 Register worker addr: tcp://127.0.0.1:39641 name: 0
INFO     distributed.scheduler:scheduler.py:6224 Starting worker compute stream, tcp://127.0.0.1:39641
INFO     distributed.core:core.py:883 Starting established connection to tcp://127.0.0.1:47442
INFO     distributed.scheduler:scheduler.py:4635 Register worker addr: tcp://127.0.0.1:38295 name: 1
INFO     distributed.scheduler:scheduler.py:6224 Starting worker compute stream, tcp://127.0.0.1:38295
INFO     distributed.core:core.py:883 Starting established connection to tcp://127.0.0.1:47458
INFO     distributed.scheduler:scheduler.py:5959 Receive client connection: MenrvaClient-6d930cff-6712-11f0-8a4d-6045bdd582b7
INFO     distributed.core:core.py:883 Starting established connection to tcp://127.0.0.1:47472
INFO     distributed.scheduler:scheduler.py:8182 Registering Worker plugin worker_logger
INFO     viperlog:logger.py:55 Client <MenrvaClient: 'tcp://127.0.0.1:41767' processes=2 threads=2, memory=14.90 GiB>
INFO     distributed.scheduler:scheduler.py:7615 Retire worker addresses (stimulus_id='retire-workers-1753198929.909512') (0, 1)
INFO     distributed.nanny:nanny.py:611 Closing Nanny at 'tcp://127.0.0.1:37567'. Reason: nanny-close
INFO     distributed.nanny:nanny.py:858 Nanny asking worker to close. Reason: nanny-close
INFO     distributed.nanny:nanny.py:611 Closing Nanny at 'tcp://127.0.0.1:42147'. Reason: nanny-close
INFO     distributed.nanny:nanny.py:858 Nanny asking worker to close. Reason: nanny-close
INFO     distributed.core:core.py:908 Received 'close-stream' from tcp://127.0.0.1:47442; closing.
INFO     distributed.scheduler:scheduler.py:5445 Remove worker addr: tcp://127.0.0.1:39641 name: 0 (stimulus_id='handle-worker-cleanup-1753198929.9121144')
INFO     distributed.core:core.py:908 Received 'close-stream' from tcp://127.0.0.1:47458; closing.
INFO     distributed.scheduler:scheduler.py:5445 Remove worker addr: tcp://127.0.0.1:38295 name: 1 (stimulus_id='handle-worker-cleanup-1753198929.9133162')
INFO     distributed.scheduler:scheduler.py:5583 Lost all workers
INFO     distributed.batched:batched.py:122 Batched Comm Closed <TCP (closed) Scheduler connection to worker local=tcp://127.0.0.1:41767 remote=tcp://127.0.0.1:47458>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/distributed/comm/tcp.py", line 298, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
             ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/distributed/comm/tcp.py", line 308, in write
    convert_stream_closed_error(self, e)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/distributed/comm/tcp.py", line 137, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Scheduler connection to worker local=tcp://127.0.0.1:41767 remote=tcp://127.0.0.1:47458>: Stream is closed
INFO     distributed.nanny:nanny.py:626 Nanny at 'tcp://127.0.0.1:42147' closed.
INFO     distributed.nanny:nanny.py:626 Nanny at 'tcp://127.0.0.1:37567' closed.
INFO     distributed.scheduler:scheduler.py:4344 Closing scheduler. Reason: unknown
INFO     distributed.scheduler:scheduler.py:4372 Scheduler closing all comms
INFO     testviper.rp_reporter:testviper_rp_reporter.py:238 TestViper RP: Test completed toolviper/tests/test_menerva.py::TestToolViperMenerva::test_thread_info (Duration: 1.20s)