ERROR    viperlog:logger.py:122 [[38;2;220;20;60miter_files_[0m]: Path not found ... : tests/data/
INFO     viperlog:logger.py:55 Function iter_files_(...) working as expected.